apiVersion: batch/v1
kind: Job
metadata:
  name: kiss-elastic-sync-job-website
  namespace: demodam-demo
spec:
  template:
    spec:
      containers:
        - name: kiss-elastic-sync
          image: ghcr.io/klantinteractie-servicesysteem/kiss-elastic-sync:0.1.2
          imagePullPolicy: Always
          args:
          - domain
          - https://www.delta10.nl
          envFrom:
          - secretRef:
              name: kiss-secrets
          - configMapRef:
              name: kiss-config
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10000
            capabilities:
              drop: [ALL]
      restartPolicy: Never
