apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: openinwoner
  namespace: demodam-demo
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - config:
      node.roles:
      - data
      - ingest
      - master
      node.store.allow_mmap: false
    count: 1
    name: default
  version: 8.9.0
