apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kiss
  namespace: demodam-demo
spec:
  config:
    server.publicBaseUrl: https://kibana.demodam.example.com
  count: 1
  elasticsearchRef:
    name: kiss
  enterpriseSearchRef:
    name: kiss
  version: 8.9.0