apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openforms
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: openforms
      version: "1.8.10"
      sourceRef:
        kind: HelmRepository
        name: maykin
  valuesFrom:
    - kind: Secret
      name: openforms-secrets
    - kind: Secret
      name: postgresql
      valuesKey: password
      targetPath: settings.database.password
  values:
    redis:
      image:
        repository: bitnamilegacy/redis

    image:
      repository: openformulieren/open-forms
      tag: 3.2.1

    settings:
      numProxies: 1
      isHttps: true
      useXForwardedHost: true

      environment: test
      showLabelEnvironment: true
      environmentLabelName: Test

      allowedHosts: localhost,formulier.example.com,openforms.openforms
      baseUrl: "https://formulier.example.com"

      database:
        host: postgresql
        username: pdv
        name: openforms

      email:
        host: ""
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@dienstverlening.example.com"

      uwsgi:
        master: true
        maxRequests: 1000
        processes: 1
        threads: 2

    worker:
      replicaCount: 1
      concurrency: 1

    persistence:
      enabled: false
      size: 10Gi

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
      className: "ingress-nginx-external"
      hosts:
       - host: formulier.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - formulier.example.com
          secretName: ingress-tls
