apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: objecten
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: objecten
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: maykin
  valuesFrom:
    - kind: Secret
      name: objecten-secrets
    - kind: Secret
      name: postgresql-cluster-app
      valuesKey: password
      targetPath: settings.database.password
  values:
    tags:
      redis: true

    redis:
      image:
        repository: bitnamilegacy/redis
      master:
        persistence:
          enabled: false

    replicaCount: 1

    image:
      repository: maykinmedia/objects-api
      pullPolicy: IfNotPresent
      tag: 3.3.1

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      className: "nginx"
      hosts:
       - host: objecten.demodam.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - objecten.demodam.example.com
          secretName: ingress-tls

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 12Mi

    persistence:
      enabled: false
      size: 1Gi
      existingClaim: null
      mediaMountSubpath: objecten/media

    global:
      configuration:
        enabled: true
        overwrite: true

    configuration:
      enabled: true
      demo:
        enabled: false
      initContainer:
        enabled: false
      job:
        enabled: true
        ttlSecondsAfterFinished: 600

      data: |-
        oidc_db_config_enable: True
        oidc_db_config_admin_auth:
          items:
          - identifier: admin-oidc
            enabled: True
            oidc_rp_client_id: registers
            oidc_rp_client_secret: IFpajZi8ktEJwwrw5Sod7clIgtZqg1WW
            oidc_rp_scopes_list:
            - openid
            - email
            - profile
            oidc_rp_sign_algo: RS256
            endpoint_config:
              oidc_op_discovery_endpoint: https://authn.demodam.example.com/realms/pdv/
            username_claim:
            - sub
            groups_claim:
            - groups
            claim_mapping:
              first_name:
              - given_name
              last_name:
              - family_name
              email:
              - email
            sync_groups: true
            sync_groups_glob_pattern: "*"
            default_groups: []
            make_users_staff: true
            superuser_group_names:
            - superuser
            oidc_use_nonce: true
            oidc_nonce_size: 32
            oidc_state_size: 32
            userinfo_claims_source: id_token

        zgw_consumers_config_enable: true
        zgw_consumers:
          services:
          - identifier: objecttypes-api
            label: Objecttypes API
            api_root: https://objecttypen.demodam.example.com/api/v2/
            api_connection_check_path: objecttypes
            api_type: orc
            auth_type: api_key
            header_key: Authorization
            header_value: Token something-secret-for-objecten
          - identifier: notifications-api
            label: Notificaties API
            api_root: https://notificaties.demodam.example.com/api/v1/
            api_connection_check_path: notificaties
            api_type: nrc
            auth_type: api_key
            header_key: Authorization
            header_value: Token something-secret-for-objecten

        notifications_config_enable: true
        notifications_config:
          notifications_api_service_identifier: notifications-api
          notification_delivery_max_retries: 1
          notification_delivery_retry_backoff: 2
          notification_delivery_retry_backoff_max: 3

        tokenauth_config_enable: true
        tokenauth:
          items:
            - identifier: openforms
              token: something-secret-for-openforms
              contact_person: openforms
              email: openforms@demodam.example.com
              is_superuser: true
            - identifier: kiss
              token: something-secret-for-kiss
              contact_person: kiss
              email: kiss@demodam.example.com
              is_superuser: true
            - identifier: nl-portal
              token: something-secret-for-nl-portal
              contact_person: nl-portal
              email: nl-portal@demodam.example.com
              is_superuser: true
            - identifier: openinwoner
              token: something-secret-for-openinwoner
              contact_person: openinwoner
              email: openinwoner@demodam.example.com
              is_superuser: true

    settings:
      allowedHosts: "localhost,objecten.demodam.example.com,objecten.objecten,kiss.demodam.example.com"
      environment: test

      database:
        host: postgresql-cluster-rw
        username: pdv
        name: objecten

      email:
        host: ""
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@dienstverlening.demodam.example.com"

      uwsgi:
        processes: 1
        threads: 2

      isHttps: true

      debug: false

      twoFactorAuthentication:
          forceOtpAdmin: true
          patchAdmin: true

    worker:
      replicaCount: 1
      concurrency: 1
      podLabels: {}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 12Mi
      maxWorkerLivenessDelta: ""
      livenessProbe: {}
        # exec:
        #   command:
        #     - python
        #     - /app/bin/check_celery_worker_liveness.py
        # initialDelaySeconds: 60
        # # Periodeseconds should not exceed maxWorkerLivenessDelta
        # periodSeconds: 10
        # timeoutSeconds: 5
        # failureThreshold: 3
        # successThreshold: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80

    flower:
      enabled: false
      replicaCount: 1
      podLabels: {}
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      resources: {}
