apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openproduct
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: openproduct
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: maykin
  valuesFrom:
    - kind: Secret
      name: openproduct-secrets
    - kind: Secret
      name: postgresql-cluster-app
      valuesKey: password
      targetPath: settings.database.password
  values:
    tags:
      redis: true

    replicaCount: 1

    image:
      repository: maykinmedia/open-product
      pullPolicy: IfNotPresent
      tag: 1.3.0

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
      className: "nginx"
      hosts:
       - host: producten.demodam.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - producten.demodam.example.com
          secretName: ingress-tls

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 12Mi

    global:
      configuration:
        enabled: true
        overwrite: true

    configuration:
      enabled: true
      initContainer:
        enabled: false
      job:
        enabled: true
        ttlSecondsAfterFinished: 600

      data: |-
        oidc_db_config_enable: True
        oidc_db_config_admin_auth:
          items:
          - identifier: admin-oidc
            enabled: True
            oidc_rp_client_id: registers
            oidc_rp_client_secret: IFpajZi8ktEJwwrw5Sod7clIgtZqg1WW
            oidc_rp_scopes_list:
            - openid
            - email
            - profile
            oidc_rp_sign_algo: RS256
            endpoint_config:
              oidc_op_discovery_endpoint: https://authn.demodam.example.com/realms/pdv/
            username_claim:
            - sub
            groups_claim:
            - groups
            claim_mapping:
              first_name:
              - given_name
              last_name:
              - family_name
              email:
              - email
            sync_groups: true
            sync_groups_glob_pattern: "*"
            default_groups: []
            make_users_staff: true
            superuser_group_names:
            - superuser
            oidc_use_nonce: true
            oidc_nonce_size: 32
            oidc_state_size: 32
            userinfo_claims_source: id_token

    settings:
      allowedHosts: "localhost,producten.demodam.example.com"
      djangoSettingsModule: openproduct.conf.docker
      useXForwardedHost: true

      environment: "test"

      database:
        host: postgresql-cluster-rw
        username: pdv
        name: openproduct

      email:
        host: ""
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@dienstverlening.demodam.example.com"

      isHttps: true
      debug: false

    persistence:
      enabled: false
      size: 1Gi
      storageClassName: ""
      existingClaim: null
      mediaMountSubpath: openproduct/media
      privateMediaMountSubpath: openproduct/private_media

    worker:
      replicaCount: 1
      concurrency: 4
      podLabels: {}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 12Mi
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80

    ##################
    # Redis subchart #
    ##################

    redis:
      image:
        repository: bitnamilegacy/redis

      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 12Mi
          limits:
            memory: 500Mi
            cpu: 500m
