apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openinwoner
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: openinwoner
      version: "1.11.2"
      sourceRef:
        kind: HelmRepository
        name: maykin
  valuesFrom:
    - kind: Secret
      name: openinwoner-secrets
    - kind: Secret
      name: postgresql-cluster-app
      valuesKey: password
      targetPath: settings.database.password
  values:
    tags:
      redis: true
      elasticsearch: false

    image:
      tag: 1.34.2

    replicaCount: 1

    global:
      configuration:
        enabled: true
        overwrite: true

    configuration:
      enabled: true
      initContainer:
        enabled: false
      job:
        enabled: true
        ttlSecondsAfterFinished: 600

      data: |-
        oidc_db_config_enable: True
        oidc_db_config_admin_auth:
          items:
          - identifier: admin-oidc
            enabled: True
            oidc_rp_client_id: registers
            oidc_rp_client_secret: IFpajZi8ktEJwwrw5Sod7clIgtZqg1WW
            oidc_rp_scopes_list:
            - openid
            - email
            - profile
            oidc_rp_sign_algo: RS256
            endpoint_config:
              oidc_op_discovery_endpoint: https://authn.demodam.example.com/realms/pdv/
            username_claim:
            - sub
            groups_claim:
            - groups
            claim_mapping:
              first_name:
              - given_name
              last_name:
              - family_name
            sync_groups: true
            sync_groups_glob_pattern: "*"
            default_groups: []
            make_users_staff: true
            superuser_group_names:
            - superuser
            oidc_use_nonce: true
            oidc_nonce_size: 32
            oidc_state_size: 32
            userinfo_claims_source: id_token
        zgw_consumers_config_enable: True
        zgw_consumers:
          services:
            - identifier: zaken-test
              label: Open Zaak - Zaken API
              api_root: https://zaken.demodam.example.com/zaken/api/v1/
              api_type: zrc
              auth_type: zgw
              client_id: openinwoner
              secret: something-secret
            - identifier: documenten-test
              label: Open Zaak - Documenten API
              api_root: https://zaken.demodam.example.com/documenten/api/v1/
              api_type: drc
              auth_type: zgw
              client_id: openinwoner
              secret: something-secret
            - identifier: catalogi-test
              label: Open Zaak - Catalogi API
              api_root: https://zaken.demodam.example.com/catalogi/api/v1/
              api_type: ztc
              auth_type: zgw
              client_id: openinwoner
              secret: something-secret
            - identifier: besluiten-test
              label: Open Zaak - Besluiten API
              api_root: https://zaken.demodam.example.com/besluiten/api/v1/
              api_type: brc
              auth_type: zgw
              client_id: openinwoner
              secret: something-secret
            - identifier: selectielijst
              label: Open Zaak (public) - Selectielijst API
              api_root: https://selectielijst.openzaak.nl/api/v1/
              api_type: orc
              auth_type: no_auth
        openzaak_config_enable: true
        openzaak_config:
          zaak_max_confidentiality: openbaar
          document_max_confidentiality: vertrouwelijk
          max_upload_size: 50
          skip_notification_statustype_informeren: false
          reformat_esuite_zaak_identificatie: true
          derive_zaak_titel_from: zaaktype_omschrijving
          order_statuses_by_date_set: false
          title_text: title text from setup configuration
          enable_categories_filtering_with_zaken: true
          action_required_deadline_days: 1874
          zaken_filter_enabled: 'true'
          allowed_file_extensions:
            - .pdf
            - .txt
          api_groups:
            - zaken_api_identifier: zaken-test
              documenten_api_identifier: documenten-test
              catalogi_api_identifier: catalogi-test
              fetch_eherkenning_zaken_with_rsin: true
        openklant_config_enable: false
        # OpenKlant2
        openklant2_config_enable: false

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
      className: "nginx"
      hosts:
       - host: portaal.demodam.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - portaal.demodam.example.com
          secretName: ingress-tls

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 12Mi

    persistence:
      enabled: false
      size: 10Gi

    settings:
      allowedHosts: "localhost,portaal.demodam.example.com,openinwoner.openinwoner"

      environment: "test"

      digidMock: "True"
      eherkenningMock: "True"

      database:
        host: postgresql-cluster-rw
        username: pdv
        name: openinwoner

      email:
        host: ""
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@demodam.example.com"

      uwsgi:
        master: ''
        threads: ''
        processes: ''
        maxRequests: ''
        harakiri: ''

      isHttps: true
      debug: false

    worker:
      replicaCount: 1
      concurrency: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 12Mi

    ##################
    # Redis subchart #
    ##################

    redis:
      image:
        repository: bitnamilegacy/redis

      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 12Mi
          limits:
            memory: 500Mi
            cpu: 500m
