apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiss
  namespace: demodam-demo
spec:
  interval: 5m
  url: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/KISS-frontend/main/helm
