apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opennotificaties
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: opennotificaties
      version: "1.11.1"
      sourceRef:
        kind: HelmRepository
        name: maykin
  valuesFrom:
    - kind: Secret
      name: opennotificaties-secrets
    - kind: Secret
      name: postgresql-cluster-app
      valuesKey: password
      targetPath: settings.database.password
  values:
    tags:
      redis: true
      rabbitmq: true

    replicaCount: 1

    image:
      repository: openzaak/open-notificaties
      pullPolicy: IfNotPresent
      tag: "1.13.0"

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    global:
      configuration:
        enabled: true
        overwrite: true

    configuration:
      enabled: true
      initContainer:
        enabled: false
      job:
        enabled: true
        ttlSecondsAfterFinished: 600

      data: |-
        oidc_db_config_enable: True
        oidc_db_config_admin_auth:
          items:
          - identifier: admin-oidc
            enabled: True
            oidc_rp_client_id: registers
            oidc_rp_client_secret: IFpajZi8ktEJwwrw5Sod7clIgtZqg1WW
            oidc_rp_scopes_list:
            - openid
            - email
            - profile
            oidc_rp_sign_algo: RS256
            endpoint_config:
              oidc_op_discovery_endpoint: https://authn.demodam.example.com/realms/pdv/
            username_claim:
            - sub
            groups_claim:
            - groups
            claim_mapping:
              first_name:
              - given_name
              last_name:
              - family_name
              email:
              - email
            sync_groups: true
            sync_groups_glob_pattern: "*"
            default_groups: []
            make_users_staff: true
            superuser_group_names:
            - superuser
            oidc_use_nonce: true
            oidc_nonce_size: 32
            oidc_state_size: 32
            userinfo_claims_source: id_token

    serviceAccount:
      create: true
      annotations: {}
      name: ""
      automountServiceAccountToken: false

    podAnnotations: {}

    podLabels: {}

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1

    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
      className: "nginx"
      hosts:
       - host: notificaties.demodam.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - notificaties.demodam.example.com
          secretName: ingress-tls

    extraIngress: []

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 12Mi

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    pdb:
      create: false
      minAvailable: 1
      maxUnavailable: ""

    nodeSelector: {}

    tolerations: []

    affinity: {}

    persistence:
      enabled: false
      size: 512Mi
      existingClaim: null
      privateMediaMountSubpath: opennotificaties/media

    azureVaultSecret:
      vaultName: null
      objectName: ""
      contentType: ""
      secretName: "{{ .Values.existingSecret }}"

    extraEnvVars: []

    extraVolumes: []

    extraVolumeMounts: []

    extraVerifyCerts: ""

    settings:
      allowedHosts: "localhost,notificaties.demodam.example.com,opennotificaties.opennotificaties"
      djangoSettingsModule: nrc.conf.docker
      useXForwardedHost: true

      logNotifications: true
      cleanOldNotifications:
        enabled: true
        daysRetained: "60"
        cronjob:
          schedule: "0 0 * * *"
          historyLimit: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 12Mi

      environment: "test"

      database:
        host: postgresql-cluster-rw
        port: 5432
        username: pdv
        name: opennotificaties
        sslmode: prefer

      numProxies: 2

      email:
        host: ""
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@dienstverlening.demodam.example.com"

      flower:
        urlPrefix: ""
        basicAuth: ""

      elasticapm:
        url: ""
        serviceName: ""

      sentry:
        dsn: ""

      cache:
        default: ""
        axes: ""

      celery:
        logLevel: debug
        brokerUrl: ""
        resultBackend: ""
        publishBrokerUrl: ""
        rabbitmqHost: ""

      isHttps: true

      debug: false

      uwsgi:
        master: ''
        threads: ''
        processes: ''
        maxRequests: ''
        harakiri: ''

    worker:
      replicaCount: 1
      concurrency: 4
      podLabels: {}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 12Mi
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80

    flower:
      enabled: false
      replicaCount: 1
      podLabels: {}
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      resources: {}

    ##################
    # Redis subchart #
    ##################

    redis:
      image:
        repository: bitnamilegacy/redis

      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 12Mi
          limits:
            memory: 500Mi
            cpu: 500m

    #####################
    # RabbitMQ subchart #
    #####################

    rabbitmq:
      image:
        repository: bitnamilegacy/rabbitmq

      auth:
        username: opennotificaties
      persistence:
        enabled: false
        size: 1Gi
        existingClaim: null
      resources:
        limits:
          memory: 1000Mi
          cpu: 500m
        requests:
          cpu: 10m
          memory: 12Mi
      rbac:
        create: false
      clustering:
        enabled: false
      serviceAccount:
        create: true
        automountServiceAccountToken: false
