apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openzaak
  namespace: demodam-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: openzaak
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: maykin
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: openzaak-secrets
    - kind: Secret
      name: postgresql-cluster-app
      valuesKey: password
      targetPath: settings.database.password
  values:
    tags:
      redis: true

    replicaCount: 1

    image:
      repository: openzaak/open-zaak
      pullPolicy: IfNotPresent
      tag: "1.25.0"

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    global:
      configuration:
        enabled: true
        overwrite: true
        notificatiesOpenzaakSecret: something-secret
        openzaakNotificatiesSecret: something-secret

    configuration:
      enabled: true
      initContainer:
        enabled: false
      job:
        enabled: true
        ttlSecondsAfterFinished: 600
      notificatiesAuthorization:
        enabled: true
      notificaties:
        enabled: true

      data: |-
        oidc_db_config_enable: True
        oidc_db_config_admin_auth:
          items:
          - identifier: admin-oidc
            enabled: True
            oidc_rp_client_id: registers
            oidc_rp_client_secret: IFpajZi8ktEJwwrw5Sod7clIgtZqg1WW
            oidc_rp_scopes_list:
            - openid
            - email
            - profile
            oidc_rp_sign_algo: RS256
            endpoint_config:
              oidc_op_discovery_endpoint: https://authn.demodam.example.com/realms/pdv/
            username_claim:
            - sub
            groups_claim:
            - groups
            claim_mapping:
              first_name:
              - given_name
              last_name:
              - family_name
              email:
              - email
            sync_groups: true
            sync_groups_glob_pattern: "*"
            default_groups: []
            make_users_staff: true
            superuser_group_names:
            - superuser
            oidc_use_nonce: true
            oidc_nonce_size: 32
            oidc_state_size: 32
            userinfo_claims_source: id_token

        zgw_consumers_config_enable: true
        zgw_consumers:
          services:
            - identifier: notifications-api
              label: Notificaties API
              api_root: https://notificaties.demodam.example.com/api/v1/
              api_connection_check_path: notificaties
              api_type: nrc
              auth_type: api_key
              header_key: Authorization
              header_value: Token something-secret

        vng_api_common_applicaties_config_enable: true
        vng_api_common_applicaties:
          items:
            - uuid: 78591bab-9a00-4887-849c-53b21a67782f
              client_ids:
              - openforms
              label: openforms
              heeft_alle_autorisaties: true
            - uuid: e65b03e9-670f-4be8-baed-046bade8b409
              client_ids:
              - kiss
              label: kiss
              heeft_alle_autorisaties: true
            - uuid: d5d005da-b33e-4e9b-b184-9a3e1f66f4a9
              client_ids:
              - nl-portal
              label: nl-portal
              heeft_alle_autorisaties: true
            - uuid: 95daa5e1-5e6c-4b81-9c42-d293e9b7b9b8
              client_ids:
              - openinwoner
              label: openinwoner
              heeft_alle_autorisaties: true
        vng_api_common_credentials_config_enable: true
        vng_api_common_credentials:
          items:
            - identifier: openforms
              secret: something-secret
            - identifier: kiss
              secret: something-secret-and-really-long
            - identifier: nl-portal
              secret: something-secret-and-really-long
            - identifier: openinwoner
              secret: something-secret

    serviceAccount:
      create: true
      annotations: {}
      name: ""
      automountServiceAccountToken: false

    podAnnotations: {}

    podLabels: {}

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000

    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1

    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
      className: "nginx"
      hosts:
       - host: zaken.demodam.example.com
         paths:
           - path: /
             pathType: ImplementationSpecific
      tls:
        - hosts:
            - zaken.demodam.example.com
          secretName: ingress-tls

    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 12Mi

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80

    pdb:
      create: false
      minAvailable: 1
      maxUnavailable: ""

    nodeSelector: {}

    tolerations: []

    affinity: {}

    persistence:
      enabled: false
      size: 20Gi
      existingClaim: null
      privateMediaMountSubpath: openzaak/private_media

    azureVaultSecret:
      vaultName: null
      objectName: ""
      contentType: ""
      secretName: "{{ .Values.existingSecret }}"

    extraEnvVars: []

    extraVolumes: []

    extraVolumeMounts: []

    extraVerifyCerts: ""

    extraDeploy: []

    settings:
      allowedHosts: "localhost,zaken.demodam.example.com,openzaak.openzaak"
      djangoSettingsModule: openzaak.conf.docker
      useXForwardedHost: true

      environment: "test"

      database:
        host: postgresql-cluster-rw
        username: pdv
        name: openzaak

      numProxies: 2

      email:
        host: ''
        port: 25
        username: ""
        useTLS: true
        defaultFrom: "noreply@dienstverlening.demodam.example.com"

      flower:
        urlPrefix: ""
        basicAuth: ""

      elasticapm:
        url: ""
        token: ""
        serviceName: ""

      sentry:
        dsn: ""

      cache:
        default: ""
        axes: ""
        portalLocker: ""

      celery:
        enabled: true
        brokerUrl: ""
        resultBackend: ""
        logLevel: debug

      jwtExpiry: 3600

      cmis:
        enabled: false
        mapperFile: ""

      isHttps: true

      debug: false

      uwsgi:
        master: ""
        threads: 4
        processes: 4
        maxRequests: ""
        harakiri: ""

    worker:
      replicaCount: 1
      concurrency: 4
      podLabels: {}
      resources: {}
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 100
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80

    nginx:
      image:
        repository: nginxinc/nginx-unprivileged
        pullPolicy: IfNotPresent
        tag: stable
      service:
        type: ClusterIP
        port: 80
        annotations: {}
      existingConfigmap: null
      replicaCount: 1
      podLabels: {}
      securityContext:
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 101
      autoscaling:
        enabled: false
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      resources: {}

    flower:
      enabled: false
      replicaCount: 1
      podLabels: {}
      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
        successThreshold: 1
      resources: {}


    ##################
    # Redis subchart #
    ##################
    redis:
      image:
        repository: bitnamilegacy/redis

      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 12Mi
